/*
SQLyog Ultimate v11.33 (64 bit)
MySQL - 5.5.58 : Database - fdaregistration
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*Table structure for table `applications` */

DROP TABLE IF EXISTS `applications`;

CREATE TABLE `applications` (
  `appid` int(11) NOT NULL AUTO_INCREMENT,
  `appname` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `category` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  PRIMARY KEY (`appid`)
) ENGINE=InnoDB AUTO_INCREMENT=37 DEFAULT CHARSET=utf8mb4;

/*Data for the table `applications` */

insert  into `applications`(`appid`,`appname`,`category`) values (1,'APPLICATION FOR FOOD HYGIENE PERMIT','food'),(2,'APPLICATION FOR FOOD IMPORTER REGISTRATION ','food'),(3,'APPLICATION FOR LICENSING OF FOOD MAUFACTURING','food'),(4,'APPLICATION FOR THE REGISTRATION OF FOOD PRODUCT','food'),(5,'APPLICATION FOR THE REGISTRATION OF IMPORTED FOOD PRODUCT','food'),(6,'APPLICATION FOR WAREHOUSE LICENSING','food'),(7,'APPLICATION FOR COLD STORAGE FACILITY LICENSING','food'),(8,'APPLICATION FOR LICENCE AS AN IMPORTER OF COSMETICS AND HOUSEHOLD CHEMICAL SUBSTANCES','drug'),(9,'APPLICATION FOR VARIATION','drug'),(10,'APPLICATION FORM FOR A LICENCE TO MANUFACTURE DRUGS, COMETICS, HOUSEHOLD CHEMICAL SUBSTANCES AND MEDICAL DEVICES','drug'),(11,'APPLICATION FORM FOR ADVERTISEMENT OF DRUGS AND OTHER REGULATED PRODUCTS','drug'),(12,'APPLICATION FORM FOR AUTHORIZED PERSONS IN  PHARMA & CHEMICAL INDUSTRY','drug'),(13,'Application Form for Blood Facility Products Listing In Ghana','drug'),(14,'APPLICATION FORM FOR HOMEOPATHIC MEDICINE','drug'),(15,'APPLICATION FORM FOR LICENSE AS AN IMPORTER OF MEDICAL DEVICES','drug'),(16,'Application Form for Licensing Blood Facilities In Ghana','drug'),(17,'APPLICATION FORM FOR LICENSING OF STORAGE FACILITIES OF   IMPORTERS, EXPORTERS, WHOLESALERS AND DISTRIBUTORS OF PHARMACEUTICAL PRODUCTS, HERBALS PRODUCTS, FOOD SUPPLEMENTS AND PHARMACEUTICAL RAW MATERIALS','drug'),(18,'APPLICATION FORM FOR REGISTRATION OF DIAPERS (BABY & ADULT), SANITARY PADS AND MOP UP TOWELS','drug'),(19,'APPLICATION FORM FOR THE REGISTRATION OF ALLOPATHIC DRUG CTD FORMAT','drug'),(20,'APPLICATION FORM FOR THE REGISTRATION OF CLASS I MEDICAL DEVICE','drug'),(21,'APPLICATION FORM FOR THE REGISTRATION OF CLASSES II -IV','drug'),(22,'APPLICATION FORM FOR VARIATIONS TO A BIOLOGICAL PRODUCT','drug'),(23,'COSMETIC APPLICATION','drug'),(24,'DISPOSAL OF EXPIRED,DETERIORATED DRUGS, COSMETICS, HOUSEHOLD CHEMICAL SUBSTANCES OR MEDICAL DEVICE','drug'),(25,'HOUSEHOLD CHEMICALS','drug'),(26,'Registration Application form for Biosimilar Products','drug'),(27,'Registration Application form for Innovator Biological Products','drug'),(28,'Registration Application form for Vaccines','drug'),(29,'REGISTRATION OF A FOOD,DIETARY , NUTRITIONAL SUPPLEMENT','drug'),(30,'RENEWAL OF LICENSE FOR THE MANUFACTURE OF DRUGS, COSMETICS, MEDICAL DEVICES AND HOUSEHOLD CHEMICAL SUBSTANCES','drug'),(31,'REGISTRATION OF HERBAL MEDICINAL PRODUCT ','drug'),(32,'TOBACCO PRODUCT REGISTRATION','drug'),(33,'TOBACCO REGISTRATION FOR IMPORTERS','drug'),(34,'VETERINARY DRUG APPLICATION FORM','drug'),(35,'VETERINARY SUPPLEMENT APPLICATION FORM ','drug');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
